{
 "title": "Toy Cluster",
 "time": { "from": "now-4d", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage % per Node",
   "type": "timeseries",
   "description": "Total CPU utilization per node",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * -100 + 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage per Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "{{instance}} read"
    },
    {
     "expr": "sum by(instance) (rate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "{{instance}} write"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_network_receive_bytes_total{device!=\"lo\"}[5m]))",
     "legendFormat": "{{instance}} in"
    },
    {
     "expr": "sum by(instance) (rate(node_network_transmit_bytes_total{device!=\"lo\"}[5m]))",
     "legendFormat": "{{instance}} out"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{\n      fstype=~\"ext4|xfs\",\n      mountpoint!~\"/var/snap/.*|/home/hpc/disk4TB\"})",
     "legendFormat": "total"
    },
    {
     "expr": "(\n  (node_filesystem_size_bytes{\n      fstype=~\"ext4|xfs\",\n      mountpoint!~\"/var/snap/.*|/home/hpc/disk4TB\"\n    } \n    - node_filesystem_free_bytes{\n      fstype=~\"ext4|xfs\",\n      mountpoint!~\"/var/snap/.*|/home/hpc/disk4TB\"\n    }\n  )\n)",
     "legendFormat": "used"
    }
   ]
  }
 ]
}